ep2c/src/main/java/br/com/ep2c/model/IEntity.java
package br.com.ep2c.model;

import java.io.Serializable;

public interface IEntity extends Serializable {

    public Integer getId();
}

ep2c/src/main/webapp/cliente/clienteDialog.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Cars</title>
	<style type="text/css">
.ui-widget {
	font-size: 90%;
}
</style>
</h:head>

<h:body>
	<h:form>
		<p:dataTable var="cliente" value="#{clienteDialog.clientes}">
			<p:column headerText="Código">
				<h:outputText value="#{cliente.id}" />
			</p:column>

			<p:column headerText="Nome">
				<h:outputText value="#{cliente.nome}" />
			</p:column>

			<p:column headerText="CPF/CNPJ">
				<h:outputText value="#{cliente.cpfCnpj}" />
			</p:column>

			<p:column style="width:32px;text-align: center">
				<p:commandButton icon="ui-icon-search"
					actionListener="#{dfCarsView.selectClienteFromDialog(cliente)}" />
			</p:column>
		</p:dataTable>
	</h:form>
</h:body>

</html>

ep2c/src/main/webapp/cliente/consultaExcluiCliente.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:composite="http://java.sun.com/jsf/composite">

<ui:composition template="/template.xhtml">
	<ui:define name="content">
		<h2>Consulta Cliente</h2>

		<h:form>
			<p:growl id="msgs" showDetail="true" />

			<h3 class="first">Clientes</h3>
			<p:dataTable var="cliente" value="#{consultaExcluiClienteMB.list}"
				tableStyleClass="ui-table-columntoggle">
				<p:column headerText="Código" priority="1">
					<h:outputText value="#{cliente.id}" />
				</p:column>
				<p:column headerText="Nome">
					<h:outputText value="#{cliente.nome}" />
				</p:column>
				<p:column headerText="Razão Social">
					<h:outputText value="#{cliente.razaoSocial}" />
				</p:column>
				<p:column headerText="CPF/CNPJ">
					<h:outputText value="#{cliente.cpfCnpj}" />
				</p:column>
				<p:column headerText="Insc. Estadual">
					<h:outputText value="#{cliente.inscEstadual}" />
				</p:column>
				<p:column headerText="Logradouro">
					<h:outputText value="#{cliente.endereco.logradouro}" />
				</p:column>
				<p:column headerText="Número">
					<h:outputText value="#{cliente.endereco.numero}" />
				</p:column>
				<p:column headerText="Bairro">
					<h:outputText value="#{cliente.endereco.bairro}" />
				</p:column>
				<p:column headerText="Cidade">
					<h:outputText value="#{cliente.endereco.cidade}" />
				</p:column>
				<p:column id="idAcoes" headerText="Ações">
					<p:commandLink id="idAcaoExcluirC_Link" value="Excluir"
						onclick="PF('dialogExcluir').show();" process="@this" ajax="true">
						<f:setPropertyActionListener value="#{cliente}"
							target="#{consultaExcluiClienteMB.tmp}" />
					</p:commandLink>
					<br />
					<p:commandLink id="idAcaoEditar" value="Editar"
						action="#{consultaExcluiClienteMB.edit}" ajax="false">
						<f:setPropertyActionListener value="#{cliente}"
							target="#{consultaExcluiClienteMB.tmp}" />
					</p:commandLink>
				</p:column>
			</p:dataTable>


			<p:dialog header="Remover cliente?" modal="true" height="100"
				id="dialogExcluir" widgetVar="dialogExcluir">
				<h:outputText value="Remover cliente?" />
				<br />
				<br />
				<p:commandButton id="idAcaoExcluirSim" value="Sim"
					action="#{consultaExcluiClienteMB.remove}" ajax="false" />

				<p:commandButton id="idAcaoExcluirNao" value="Não"
					onclick="PF('dialogExcluir').hide()" ajax="false" />
			</p:dialog>

		</h:form>
	</ui:define>
</ui:composition>

</html>

ep2c/src/main/webapp/cliente/inseriAtualizaCliente.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:composite="http://java.sun.com/jsf/composite">

<ui:composition template="/template.xhtml">
	<ui:define name="content">
		<h2>Cliente</h2>
			<h:form>
				<p:messages id="messages" />
				<p:outputLabel value="Código:" />
				<br />
				<p:inputText id="idCliente" value="#{inseriAtualizaClienteMB.cliente.id}"
					disabled="true" />
				<br />
				<p:outputLabel value="Nome:" />
				<br />
				<p:inputText id="idNomeCliente" value="#{inseriAtualizaClienteMB.cliente.nome}"
					size="40" maxlength="40" required="true" />
				<br />
				<p:outputLabel value="Razão Social:" />
				<br />
				<p:inputText id="idRazaoSocialCliente"
					value="#{inseriAtualizaClienteMB.cliente.razaoSocial}" size="40" maxlength="40" />
				<br />
				<p:outputLabel value="CPF/CNPJ:" />
				<br />
				<p:inputText id="idCpfCnpjCliente"
					value="#{inseriAtualizaClienteMB.cliente.cpfCnpj}" size="40" maxlength="14" required="true" />
				<br />
				<p:outputLabel value="Inscrição Estadual:" />
				<br />
				<p:inputText id="idInscEstadualCliente"
					value="#{inseriAtualizaClienteMB.cliente.inscEstadual}" size="40" maxlength="16"/>
				<br />
				<p:outputLabel value="Endereço:" />
				<br />
				<p:outputLabel for="logradouro" value="Logradouro:" />
				<br />
				<p:selectOneMenu id="logradouro"
					value="#{inseriAtualizaClienteMB.cliente.endereco.tipoLogradouro}">
					<f:selectItem itemLabel="Rua" itemValue="Rua" />
					<f:selectItem itemLabel="Avenida" itemValue="Av" />
					<f:selectItem itemLabel="Travessa" itemValue="Travessa" />
					<f:selectItem itemLabel="Vila" itemValue="Vila" />
				</p:selectOneMenu>
				<br />
				<p:inputText id="idLogradouroEndereco"
					value="#{inseriAtualizaClienteMB.cliente.endereco.logradouro}" size="40" maxlength="40" />
				<br />
				<p:outputLabel value="Número:" />
				<br />
				<p:inputText id="idNumeroEndereco"
					value="#{inseriAtualizaClienteMB.cliente.endereco.numero}" size="40" maxlength="12"/>
				<br />
				<p:outputLabel value="Bairro:" />
				<br />
				<p:inputText id="idBairroEndereco"
					value="#{inseriAtualizaClienteMB.cliente.endereco.bairro}" size="40" maxlength="40" />
				<br />
				<p:outputLabel value="Cidade:" />
				<br />
				<p:inputText id="idCidadeEndereco"
					value="#{inseriAtualizaClienteMB.cliente.endereco.cidade}" size="40" maxlength="40"/>
				<br />
				<p:outputLabel value="UF:" />
				<br />
				<p:inputText id="idUFEndereco"
					value="#{inseriAtualizaClienteMB.cliente.endereco.uf}" size="2" maxlength="2"/>
				<br />
				<p:outputLabel value="Complemento:" />
				<br />
				<p:inputText id="idComplementoEndereco"
					value="#{inseriAtualizaClienteMB.cliente.endereco.complemento}" size="40" maxlength="100" />
				<br />
				<p:outputLabel value="CEP:" />
				<br />
				<p:inputText id="idCepEndereco"
					value="#{inseriAtualizaClienteMB.cliente.endereco.cep}" size="40" maxlength="9" />
				<br />
				<p:commandButton value="Salvar" icon="ui-icon-star"
					action="#{inseriAtualizaClienteMB.salvar}" ajax="false">
				</p:commandButton>
				<p:commandButton value="Novo" icon="ui-icon-star"
					action="#{inseriAtualizaClienteMB.novo}" ajax="false">
				</p:commandButton>
			</h:form>
	</ui:define>
</ui:composition>

</html>