ep2c/src/main/java/br/com/ep2c/view/managedbean/UsuarioMB.java
package br.com.ep2c.view.managedbean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

import org.apache.commons.lang3.StringUtils;
import org.apache.log4j.Logger;

import br.com.ep2c.facade.FuncionarioEntityFacade;
import br.com.ep2c.facade.LoginEntityFacade;
import br.com.ep2c.facade.UsuarioEntityFacade;
import br.com.ep2c.model.FuncionarioEntity;
import br.com.ep2c.model.LoginEntity;
import br.com.ep2c.model.Perfil;
import br.com.ep2c.model.UsuarioEntity;
import br.com.ep2c.util.Constants;
import br.com.ep2c.util.PasswdUtil;

@ManagedBean
@ViewScoped
public class UsuarioMB implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -5224398763815832658L;

    private static final Logger log = Logger.getLogger(UsuarioMB.class);

    private List<UsuarioEntity> list;
    private UsuarioEntity entity;
    private String confirmacao;

    private List<FuncionarioEntity> funcionarios;
    private UsuarioEntityFacade facade;
    private FuncionarioEntityFacade funcionarioFacade;

    private LoginEntityFacade loginEntityFacade;

    private Perfil perfil;

    private UsuarioEntity tmp;

    public UsuarioEntityFacade getFacade() {
	if (facade == null) {
	    facade = new UsuarioEntityFacade();
	}
	return facade;
    }

    public FuncionarioEntityFacade getFuncionarioFacade() {
	if (funcionarioFacade == null) {
	    funcionarioFacade = new FuncionarioEntityFacade();
	}
	return funcionarioFacade;
    }

    public LoginEntityFacade getLoginEntityFacade() {
	if (loginEntityFacade == null) {
	    loginEntityFacade = new LoginEntityFacade();
	}
	return loginEntityFacade;
    }

    public String remove() {
	log.debug("No metodo remove");
	try {
	    log.debug("item[" + tmp + "]");
	    getFacade().delete(tmp);
	    initialize();
	} catch (Throwable e) {
	    FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(
		    FacesMessage.SEVERITY_ERROR, "Erro ao remover item", "Erro Pedido"));
	    e.printStackTrace();
	}
	return "#";
    }

    @PostConstruct
    public void initialize() {
	log.debug("No metodo initialize");

	HttpServletRequest rq = (HttpServletRequest) FacesContext.getCurrentInstance()
		.getExternalContext().getRequest();

	LoginMB mb = (LoginMB) rq.getSession().getAttribute(Constants.LOGIN_MB);

	list = loadUsuarios(mb);
	if (entity == null) {
	    initializeUsuarioEntity();
	}

	loadFuncionarios();
    }

    private List<UsuarioEntity> loadUsuarios(LoginMB mb) {
	UsuarioEntity e = getFacade().searchOneByField("login", mb.getLogin());
	boolean isAdmin = false;
	if (e.getPerfil().equals(Perfil.Admin.getCodigo())) {
	    isAdmin = true;
	}
	if (isAdmin) {
	    return getFacade().list();
	}
	List<UsuarioEntity> list = new ArrayList<UsuarioEntity>();
	UsuarioEntity tmp = getFacade().getUsuarioByPerfil(mb.getLogin());
	if (tmp != null) {
	    list.add(tmp);
	}
	return list;
    }

    private void loadFuncionarios() {
	log.debug("No metodo loadFuncionarios");
	List<FuncionarioEntity> funcs = getFuncionarioFacade().listByNotUsed();
	if (entity.getId() != null) {
	    funcs.add(entity.getFuncionario());
	}
	setFuncionarios(sortFuncionario(funcs));
    }

    public void novo() {
	log.debug("No metodo novo");
	initializeUsuarioEntity();
	loadFuncionarios();
    }

    private void initializeUsuarioEntity() {
	log.debug("No metodo initializeUsuarioEntity");
	entity = new UsuarioEntity();
	entity.setLogin(new LoginEntity());
	entity.setFuncionario(getFuncionarioEmpty());
    }

    public String editar() {
	log.debug("No metodo editar[" + tmp + "]");
	initializeUsuarioEntity();
	this.entity = this.tmp;
	loadFuncionarios();
	return "#";
    }

    public void salvar() {

	try {
	    if (validate()) {

		entity.getLogin()
			.setPassword(PasswdUtil.encript(entity.getLogin().getPassword()));

		getFacade().saveOrUpdate(entity);
		entity = null;
		initialize();
	    }
	} catch (Throwable e) {
	    FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(
		    FacesMessage.SEVERITY_ERROR, "Erro ao salvar entity", "Erro entity"));
	    e.printStackTrace();
	}
    }

    public void enableSenha() {

	try {
	    validate();

	    // getFacade().saveOrUpdate(entity);
	} catch (Throwable e) {
	    FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(
		    FacesMessage.SEVERITY_ERROR, "Erro ao salvar entity", "Erro entity"));
	    e.printStackTrace();
	}
    }

    private boolean validate() {
	StringBuilder builder = new StringBuilder();
	if (StringUtils.isEmpty(entity.getLogin().getLogin())) {

	    builder.append("Login é obrigatório");
	    builder.append(System.getProperty("line.separator"));
	} else {
	    if (entity.getLogin().getId() == null) {

		if (!getLoginEntityFacade().isValid(entity.getLogin().getLogin())) {
		    builder.append("Login já está em uso");
		    builder.append(System.getProperty("line.separator"));
		}
	    }
	}

	if (!StringUtils.equals(entity.getLogin().getPassword(), this.confirmacao)) {
	    builder.append("Erro na Senha e Confirmação de senha");
	    builder.append(System.getProperty("line.separator"));
	}
	if (StringUtils.isEmpty(entity.getLogin().getPassword())) {
	    builder.append("Senha é obrigatório");
	    builder.append(System.getProperty("line.separator"));
	}

	if (builder.length() > 0) {
	    FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(
		    FacesMessage.SEVERITY_ERROR, builder.toString(), "Erro entity"));
	    return false;
	}
	return true;
    }

    public List<FuncionarioEntity> sortFuncionario(List<FuncionarioEntity> list) {

	Collections.sort(list, new Comparator<FuncionarioEntity>() {

	    public int compare(FuncionarioEntity o1, FuncionarioEntity o2) {
		return (o1.getNome()).compareTo((o2.getNome()));
	    }
	});
	return list;
    }

    private FuncionarioEntity getFuncionarioEmpty() {
	FuncionarioEntity f = new FuncionarioEntity();
	f.setNome("");
	return f;
    }

    public UsuarioEntity getEntity() {
	return entity;
    }

    public void setEntity(UsuarioEntity entity) {
	this.entity = entity;
    }

    public List<UsuarioEntity> getList() {
	return list;
    }

    public void setList(List<UsuarioEntity> list) {
	this.list = list;
    }

    public List<FuncionarioEntity> getFuncionarios() {
	return funcionarios;
    }

    public void setFuncionarios(List<FuncionarioEntity> funcionarios) {
	this.funcionarios = funcionarios;
    }

    public String getConfirmacao() {
	return confirmacao;
    }

    public void setConfirmacao(String confirmacao) {
	this.confirmacao = confirmacao;
    }

    public Perfil getPerfil() {
	return perfil;
    }

    public void setPerfil(Perfil perfil) {
	this.perfil = perfil;
    }

    public Perfil[] getPerfis() {
	HttpServletRequest rq = (HttpServletRequest) FacesContext.getCurrentInstance()
		.getExternalContext().getRequest();
	LoginMB mb = (LoginMB) rq.getSession().getAttribute(Constants.LOGIN_MB);
	UsuarioEntity e = getFacade().searchOneByField("login", mb.getLogin());
	if (e.getPerfil().equals(Perfil.Admin.getCodigo())) {
	    return Perfil.values();
	}
	Perfil[] p = { Perfil.UserFunc, Perfil.UserSystem };
	return p;
    }

    public UsuarioEntity getTmp() {
	return tmp;
    }

    public void setTmp(UsuarioEntity tmp) {
	this.tmp = tmp;
    }
}

ep2c/src/main/webapp/usuario/usuario.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:composite="http://java.sun.com/jsf/composite">

<ui:composition template="/template.xhtml">
	<ui:define name="content">

		<h2>Usuário</h2>
		<h:form>
			<p:messages id="messages" />

			<p:outputLabel value="Funcionário:" />
			<br />
			<p:selectOneMenu id="idFuncionarioSelectOneMenu"
				value="#{usuarioMB.entity.funcionario}"
				converter="funcionarioConverter">
				<f:selectItem itemLabel=""/>
				<f:selectItems value="#{usuarioMB.funcionarios}" var="f"
					itemLabel="#{f.nome}" itemValue="#{f}" />
			</p:selectOneMenu>


			<br />
			<p:outputLabel value="Login:" />
			<br />
			<p:inputText id="idLogin" value="#{usuarioMB.entity.login.login}"
				size="40" maxlength="40"
				disabled="#{not empty usuarioMB.entity.login.id}" />
			<br />
			<p:outputLabel value="Senha:" />
			<br />
			<p:password id="idSenha1" value="#{usuarioMB.entity.login.password}" />
			<br />
			<p:outputLabel value="Confirmação de Senha:" />
			<br />
			<p:password id="idSenha2" value="#{usuarioMB.confirmacao}" />
			<br />
			<br />
			<p:outputLabel value="Perfil:" />
			<br />
			<p:selectOneMenu id="idPerfil" value="#{usuarioMB.entity.perfil}">
				<f:selectItem itemLabel="" itemValue="-1" />
				<f:selectItems value="#{usuarioMB.perfis}" var="p"
					itemLabel="#{p.nome}" itemValue="#{p.codigo}" />
			</p:selectOneMenu>
			<br />
			<p:commandButton value="Salvar" action="#{usuarioMB.salvar}"
				ajax="false" update="idItens" />
			<p:commandButton value="Novo" action="#{usuarioMB.novo}"
				ajax="false" update="idItens" />

			<h3 class="first">Usuários</h3>

			<p:dataTable id="idItens" var="item" value="#{usuarioMB.list}"
				tableStyleClass="ui-table-columntoggle">
				<p:column headerText="Código" priority="1">
					<h:outputText value="#{item.id}" />
				</p:column>
				<p:column headerText="Nome" priority="1">
					<h:outputText value="#{item.funcionario.nome}" />
				</p:column>
				<p:column headerText="Data de Criação" priority="1">
					<h:outputText value="#{item.funcionario.dataCriacao}" />
				</p:column>
				<p:column headerText="Login" priority="1">
					<h:outputText value="#{item.login.login}" />
				</p:column>

				<p:column id="idAcoes" headerText="Ações">
					<p:commandLink id="idAcaoExcluirC_Link" value="Excluir"
						onclick="PF('dialogExcluir').show();" process="@this" ajax="true">
						<f:setPropertyActionListener value="#{item}"
							target="#{usuarioMB.tmp}" />
					</p:commandLink>
					<p:outputLabel value=" | " />
					<p:commandLink id="idAcaoEditar" value="Editar"
						action="#{usuarioMB.editar}" ajax="false">
						<f:setPropertyActionListener value="#{item}"
							action="#{usuarioMB.editar}" target="#{usuarioMB.tmp}" />
					</p:commandLink>
					<br />
				</p:column>
			</p:dataTable>

			<!-- MODAL -->
			<p:dialog header="Remover Item?" modal="true" height="100"
				id="dialogExcluir" widgetVar="dialogExcluir">
				<h:outputText value="Remover Item?" />
				<br />
				<br />
				<p:commandButton id="idAcaoExcluirSim" value="Sim"
					action="#{usuarioMB.remove}" ajax="false" />

				<p:commandButton id="idAcaoExcluirNao" value="Não"
					onclick="PF('dialogExcluir').hide()" ajax="false" />
			</p:dialog>

		</h:form>
	</ui:define>
</ui:composition>

</html>